In [24]:
import numpy as np
dcs_n = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1])
alert_n = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

first_zero = np.where(alert_n == 0)[0][0]
print(first_zero)
search_seq = [0,0,1,1,0,0,1,1]
counter = first_zero
while counter:
    sub_seq = dcs_n[counter-8:counter]
    print(sub_seq)
    if all(sub_seq == search_seq):
        break
    counter += -1
rcd_latency = first_zero - counter
print(rcd_latency)
print(f"search seq found at {counter-8}:{counter}")

start_seq = counter -8
print(dcs_n[start_seq:start_seq+8])

dc = dcs_n[start_seq:]
print(dcs_n)
print(dc)

25
[0 1 1 0 0 1 1 0]
[0 0 1 1 0 0 1 1]
1
search seq found at 16:24
[0 0 1 1 0 0 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0
 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1]
[0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1
 1 1 1]


In [10]:
import numpy as np
dcs_n=np.array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1])
dca=np.array([127,  63, 127,  56, 127,  63, 127,  63, 127,  63,  63,  37, 127,
        63, 127,  63, 127,  63,  95,  32, 127,  63, 127,  63, 127,  63,
        95,  35, 127,  63, 127,  63, 127,  63,  69,   0,   0,   8, 127,
        63, 127,  63])
dpar=np.array([1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
alert_n=np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


dcs_n_id = np.where(dcs_n==0)[0]

print(np.shape(dcs_n_id))
print(dcs_n_id[::2])
dcs_n_split = np.array_split(dcs_n,dcs_n_id[::2])
print(dcs_n_split)

# print(dcs_n_id[0:2:4])
# dcs_n_diff = np.diff(dcs_n)
# print(dcs_n_diff)


(10,)
[ 2 10 18 26 34]
[array([1, 1]), array([0, 0, 1, 1, 1, 1, 1, 1]), array([0, 0, 1, 1, 1, 1, 1, 1]), array([0, 0, 1, 1, 1, 1, 1, 1]), array([0, 0, 1, 1, 1, 1, 1, 1]), array([0, 0, 1, 1, 1, 1, 1, 1])]


In [27]:
output = 46
xor = output & 0x01
print(f"xor={xor}")
for id in range(output.bit_length()):
    if id == 0:
        continue
    print(f"old xor={xor}")
    next_bit = (output & (0x01 << (id))) >> id
    print(f"Next bit {next_bit}")
    xor ^= next_bit
    print(f"new xor={xor}")
    print('***')    
print('----Finished')
print(f"xor={xor}")

xor=0
old xor=0
Next bit 1
new xor=1
***
old xor=1
Next bit 1
new xor=0
***
old xor=0
Next bit 1
new xor=1
***
old xor=1
Next bit 0
new xor=1
***
old xor=1
Next bit 1
new xor=0
***
----Finished
xor=0


In [29]:
output = 251
xor = output & 0x01
for id in range(output.bit_length()):
    if id == 0:
        continue
    next_bit = (output & (0x01 << (id))) >> id
    xor ^= next_bit
print(xor)

1
