In [14]:
import numpy as np
dcs_n = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1])
alert_n = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

first_zero = np.where(alert_n == 0)[0][0]
print(first_zero)
search_seq = [1,1,0,0,1,1,0,0]
counter = first_zero
while counter:
    sub_seq = dcs_n[counter-8:counter]
    print(sub_seq)
    if all(sub_seq == search_seq):
        break
    counter += -1

print(f"search seq found at {counter-8}:{counter}")

start_seq = counter -8

25
[0 1 1 0 0 1 1 0]
[0 0 1 1 0 0 1 1]
[1 0 0 1 1 0 0 1]
[1 1 0 0 1 1 0 0]
search seq found at 14:22
