In [50]:
import numpy as np
l = [3, 3, 3, 3, 0, 1, 2, 1, 1, 3, 3, 3, 3, 3]
l_np = np.array(l)
tt = l_np != 3
a = l_np[l_np != 3]
p = np.where(l_np != 3)[0][0]
q = l_np.shape[0] - 1 - np.where(l_np != 3)[0][-1]
print(a,p,q,tt)


[0 1 2 1 1] 4 5 [False False False False  True  True  True  True  True False False False
 False False]


In [61]:
import numpy as np
l = [3, 3, 3, 3, 0, 1, 2, 1, 1, 3, 3, 3, 3, 3, 0, 2, 1, 3, 3, 0,1,2,3,3,3]
l_np = np.array(l)


p = np.where(l_np != 3)
print("p=",end='')
print(p[0])

q = np.where(l_np == 3)
qt = np.where(q)

d_np = l_np != 3
diff = np.diff(d_np,prepend=np.nan)
print(diff)
l_diff = np.where(diff)
print(l_diff[0])

print(t)
r =np.array_split(l_np,p[0])

print("r=",end='')
print(r)




p=[ 4  5  6  7  8 14 15 16 19 20 21]
[nan  0.  0.  0.  1.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1.  0.  0. -1.
  0.  1.  0.  0. -1.  0.  0.]
[ 0  4  9 14 17 19 22]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]
r=[array([3, 3, 3, 3]), array([0]), array([1]), array([2]), array([1]), array([1, 3, 3, 3, 3, 3]), array([0]), array([2]), array([1, 3, 3]), array([0]), array([1]), array([2, 3, 3, 3])]


In [34]:
x=np.arange(9)
d=np.split(x,3)
print(d)
dd = np.array_split(x,[2,3,4])
print(dd)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1]), array([2]), array([3]), array([4, 5, 6, 7, 8])]


In [87]:
import numpy as np
l = [3, 3, 3, 3, 0, 1, 1, 2, 1, 3, 3, 3, 3, 3, 0, 2, 1, 3, 3, 0,1,2,3,3,3]
print(l)
l_np = np.array(l)

d_np = l_np != 3

diff = np.diff(d_np)
print(diff)
l_diff = np.where(diff)
print(l_diff[0])


D = l_diff[0]+1
print(l_np[D[1::2]])
# for every other mask_index if *(mask-2) == 2 then increase mask_index +2
D[1::2] += 2*(l_np[D[1::2]-2]==2)
print(D)
dd = np.array_split(l_np,D)
print(dd)


[3, 3, 3, 3, 0, 1, 1, 2, 1, 3, 3, 3, 3, 3, 0, 2, 1, 3, 3, 0, 1, 2, 3, 3, 3]
[False False False  True False False False False  True False False False
 False  True False False  True False  True False False  True False False]
[ 3  8 13 16 18 21]
[3 3 3]
[ 4 11 14 19 19 22]
[array([3, 3, 3, 3]), array([0, 1, 1, 2, 1, 3, 3]), array([3, 3, 3]), array([0, 2, 1, 3, 3]), array([], dtype=int64), array([0, 1, 2]), array([3, 3, 3])]


In [93]:
import numpy as np
dcs_n = [3, 3, 3, 3, 0, 1, 1, 2, 1, 3, 3, 3, 3, 3, 0, 2, 1, 3, 3, 0,1,2,3,3,3]
print(dcs_n)
dcs_n_np = np.array(dcs_n)
"""
    Find where value changes
"""
dcs_n_np_mask = l_np != 3
diff_mask = np.diff(dcs_n_np_mask)
diff_indices = np.where(diff)[0]

D = diff_indices+1
print(D)
"""
    for every other mask_index if *(mask-2) == 2 then increase mask_index +2
"""
D[1::2] += 2*(l_np[D[1::2]-2]==2)
print(D)
D_split = np.array_split(l_np,D)
print(D_split)

[3, 3, 3, 3, 0, 1, 1, 2, 1, 3, 3, 3, 3, 3, 0, 2, 1, 3, 3, 0, 1, 2, 3, 3, 3]
[ 4  9 14 17 19 22]
[ 4 11 14 19 19 22]
[array([3, 3, 3, 3]), array([0, 1, 1, 2, 1, 3, 3]), array([3, 3, 3]), array([0, 2, 1, 3, 3]), array([], dtype=int64), array([0, 1, 2]), array([3, 3, 3])]


In [161]:
dcs_n = [0, 0, 0, 0, 0, 0, 0, 0, 3, 3]
dcs_n_np = np.array(dcs_n)
dca = [2,  0,  2,  2,  0,  2,  2,  2,  2,   0]
dca_np = np.array(dca)

print(dca_np.shape[0])

evens = np.tile([1,0],int(dca_np.shape[0]/2))
print(evens)
# tmp = np.where(dca_np[evens])

print(dcs_n_np[dcs_n_np[1::2]])
is_cw_bit_set = 1*((dca_np & 0x02) == 0x02)
is_cw_bit_not_set = 1*((dca_np & 0x02) == 0x00)

print(is_cw_bit_set)
print(is_cw_bit_not_set)

evens_and_is_cw_bit_not_set = np.logical_and(evens,is_cw_bit_not_set)
print(evens_and_is_cw_bit_not_set)
# tmp = np.where(dca_np[evens_and_is_cw_bit_not_set])


10
[1 0 1 0 1 0 1 0 1 0]
[0 0 0 0 0]
[1 0 1 1 0 1 1 1 1 0]
[0 1 0 0 1 0 0 0 0 1]
[False False False False  True False False False False False]
(array([0, 2, 3, 5]),)


In [25]:
import numpy as np

dcs_n = [1,2,0,0,3,3,1,99,2,0,0,3,1,2]
dca = [2,1,0,1,34,34,99,99,0,1,1,1,2,1]

dcs_n_np = np.array(dcs_n)
dca_np = np.array(dca)

evens = np.tile([1,0],int(dca_np.shape[0]/2))
print(evens)
for id, item in enumerate(dca):
    if id < (len(dca)-2):
        if not (id%2):
            if evens[id]:
                is_cw_bit_set = ( (dca[id] & 0x02) == 0x02)
                print(id,is_cw_bit_set)
                if not is_cw_bit_set:
                    print("zeroing" + str(id))
                    evens[id+2] = 0
print(evens)
index = np.where(evens==1)
index = index[0]
print(index)
DCS_split = np.array_split(dcs_n_np,index)
print(DCS_split)
DCA_split = np.array_split(dca_np,index)
print(DCA_split)

[1 0 1 0 1 0 1 0 1 0 1 0 1 0]
0 True
2 False
zeroing2
6 True
8 False
zeroing8
[1 0 1 0 0 0 1 0 1 0 0 0 1 0]
[ 0  2  6  8 12]
[array([], dtype=int64), array([1, 2]), array([0, 0, 3, 3]), array([ 1, 99]), array([2, 0, 0, 3]), array([1, 2])]
[array([], dtype=int64), array([2, 1]), array([ 0,  1, 34, 34]), array([99, 99]), array([0, 1, 1, 1]), array([2, 1])]
